version: '3.3'

services:
  consul:
    image: consul
    ports:
      - 8500:8500

  apigateway:
    image: muccijacopo/asw-api-gateway
    ports:
      - 8080:8080
    depends_on:
      - consul

  ricette-seguite:
    deploy:
      replicas: 4
    image: muccijacopo/asw-ricette-seguite
    ports:
      - 7090:8080
    depends_on:
      - consul
      - ricette-seguite-db
      - zookeeper
      - kafka
      - ricette
      - connessioni

  ricette-seguite-db:
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagnam
      MYSQL_USER: asw-user
      MYSQL_PASSWORD: asw-user

  ricette:
    image: muccijacopo/asw-ricette
    ports:
      - 7070:8080
    deploy:
      replicas: 4

  ricette-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagnam
      MYSQL_USER: asw-user
      MYSQL_PASSWORD: asw-user
    logging:
      driver: none

  connessioni:
    image: muccijacopo/asw-connessioni
    ports:
      - 7080:8080
    depends_on:
      - consul
      - connessioni-db
      - zookeeper
      - kafka

  connessioni-db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagnam
      MYSQL_USER: asw-user
      MYSQL_PASSWORD: asw-user

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "asw.channel.ricette:1:1,asw.channel.connessioni:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
