version: '3.3'
services:

  consul:
    container_name: asw-consul
    image: consul
    ports:
      - 8500:8500
    logging:
      driver: none

  apigateway:
    container_name: asw-apigateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - consul
    logging:
      driver: none

  ricette-seguite:
    container_name: asw-ricette-seguite
    build:
      context: ricette-seguite
      dockerfile: Dockerfile
    ports:
      - 7090:8080
    depends_on:
      - consul
      - zookeeper
      - kafka
    logging:
      driver: none

  ricette:
    container_name: asw-ricette
    build:
      context: ricette
      dockerfile: Dockerfile
    ports:
      - 7070:8080
    depends_on:
      - consul
      - ricette-db
      - zookeeper
      - kafka
    # logging:
    #   driver: none

  ricette-db:
    container_name: asw-ricette-db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagnam
      MYSQL_USER: asw-user
      MYSQL_PASSWORD: asw-user
    logging:
      driver: none

  connessioni:
    container_name: asw-connessioni
    build:
      context: connessioni
      dockerfile: Dockerfile
    ports:
      - 7080:8080
    depends_on:
      - consul
      - connessioni-db
      - zookeeper
      - kafka
    logging:
      driver: none

  connessioni-db:
    container_name: asw-connessioni-db
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instagnam
      MYSQL_USER: asw-user
      MYSQL_PASSWORD: asw-user
    logging:
      driver: none

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
#    logging:
#      driver: none
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-10.11.1.121}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "asw.kafka.channel.ricette:1:1,asw.kafka.channel.connessioni:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    logging:
#      driver: none