apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: instagnam
      service: zookeeper
  template:
    metadata:
      labels:
        app: instagnam
        service: zookeeper
    spec:
      containers:
        - image: wurstmeister/zookeeper
          name: asw-zookeeper
          ports:
            - containerPort: 2181
              name: zookeeper

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: instagnam
      service: kafka
  template:
    metadata:
      labels:
        app: instagnam
        service: kafka
    spec:
      containers:
        - image: wurstmeister/kafka
          name: asw-kafka
          env:
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CREATE_TOPICS
              value: "asw.channel.ricette:1:1,asw.channel.connessioni:1:1"
          ports:
            - containerPort: 9092
              name: kafka

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ricette
spec:
  selector:
    matchLabels:
      app: instagnam
      service: ricette
  template:
    metadata:
      labels:
        app: instagnam
        service: ricette
    spec:
      containers:
        - image: adelloste/instagnam-ricette-kube:2020.0.0.2
          name: asw-ricette
          ports:
            - containerPort: 8080
              name: ricette

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ricette-seguite
spec:
  selector:
    matchLabels:
      app: instagnam
      service: ricette-seguite
  template:
    metadata:
      labels:
        app: instagnam
        service: ricette-seguite
    spec:
      containers:
        - image: adelloste/instagnam-ricette-seguite-kube:2020.0.0.2
          name: asw-ricette-seguite
          ports:
            - containerPort: 8080
              name: ricette-seguite

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ricette-db
spec:
  selector:
    matchLabels:
      app: instagnam
      service: ricette-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: instagnam
        service: ricette-db
    spec:
      containers:
        - image: mysql:5.7
          name: asw-ricette-db
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: instagnam
            - name: MYSQL_USER
              value: asw-user
            - name: MYSQL_PASSWORD
              value: asw-user
          ports:
            - containerPort: 3306
              name: ricette-db

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ricette-seguite-db
spec:
  selector:
    matchLabels:
      app: instagnam
      service: ricette-seguite-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: instagnam
        service: ricette-seguite-db
    spec:
      containers:
        - image: mysql:5.7
          name: asw-ricette-seguite-db
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: instagnam
            - name: MYSQL_USER
              value: asw-user
            - name: MYSQL_PASSWORD
              value: asw-user
          ports:
            - containerPort: 3306
              name: ricette-seg-db

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: instagnam
    service: zookeeper
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: instagnam
    service: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: ricette
spec:
  selector:
    app: instagnam
    service: ricette
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ricette-db
spec:
  selector:
    app: instagnam
    service: ricette-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: ricette-seguite
spec:
  selector:
    app: instagnam
    service: ricette-seguite
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ricette-seguite-db
spec:
  selector:
    app: instagnam
    service: ricette-seguite-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None


#---
#
#kind: Ingress
#apiVersion: extensions/v1beta1
#metadata:
#  name: instagnam
#spec:
#  rules:
#    - host: instagnam
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: apigateway
#              servicePort: 8080