# application.yml 
---
spring:
  application:
    name: apigateway
  cloud:
    loadbalancer:
      ribbon.enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ricette_seguite_route
          uri: http://ricette-seguite:8080
          predicates:
            - Path=/ricette-seguite
          filters:
            - SetPath=/
        - id: ricette_route
          uri: http://ricette:8080
          predicates:
            - Path=/ricette
          filters:
            - SetPath=/
        - id: connessioni_route
          uri: http://connessioni:8080
          predicates:
            - Path=/connessioni
          filters:
            - SetPath=/

server:
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: info,health,gateway,beans

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.cloud.gateway: INFO
