# application.yml
--- 
spring: 
  application: 
    name: ricette
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        healthCheckCriticalTimeout: 60s
        queryPassing: true
    loadbalancer:
      ribbon.enabled: false
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true
      show-sql: true
  datasource:
    url: jdbc:mysql://ricette-db:3306/ricette
    username: asw
    password: asw

server: 
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8080

# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV

