# application.yml
---
spring:
  application:
    name: connessioni
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        # configurazione per effettuare esprimenti, NON USARE UN PRODUZIONE
        # dopo quanto tempo consul deve smettere di restituire servizi che non rispondono all'health check?
        healthCheckCriticalTimeout: 60s
        # consul deve restituire solo servizi che passano l'health check (default=false)
        queryPassing: true
    loadbalancer:
      ribbon.enabled: false
  datasource:
    url: jdbc:mysql://connessioni-db:3306/instagnam
    username: asw-user
    password: asw-user
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  # port: ${PORT:${SERVER_PORT:0}}
  port: 8080

# fa il logging dei comandi sql eseguiti
# spring.jpa.show-sql: true
# disable OSIV
# spring.jpa.open-in-view: false