# application.yml
---
asw:
  kafka:
    channel:
      out: asw.channel.connessioni
spring:
  application:
    name: connessioni
  cloud:
    loadbalancer:
      ribbon.enabled: false
  datasource:
    url: jdbc:mysql://connessioni-db:3306/instagnam
    username: asw-user
    password: asw-user
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080
