apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: connessioni-db
  name: connessioni-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connessioni-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: connessioni-db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: instagnam
        - name: MYSQL_PASSWORD
          value: asw-user
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_ROOT_USER
          value: root
        - name: MYSQL_USER
          value: asw-user
        image: mysql:5.7
        imagePullPolicy: ""
        name: asw-connessioni-db
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
