apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: connessioni
  name: connessioni
spec:
  ports:
  - name: "7080"
    port: 7080
    targetPort: 8080
  selector:
    io.kompose.service: connessioni
status:
  loadBalancer: {}
