apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ricette-seguite-db
  name: ricette-seguite-db
spec:
  ports:
  - name: "3308"
    port: 3308
    targetPort: 3306
  selector:
    io.kompose.service: ricette-seguite-db
status:
  loadBalancer: {}
